### ISSUE TITLE
Screenshot

### ISSUE THREAD

**Issue by GoogleCodeExporter** [CaptainSpam/geohashdroid#44]
```
The app needs the ability to screenshot itself for proof that you have reached 
the location.
```

Original issue reported on code.google.com by `millerswebsite` on 25 Aug 2012 at 3:02

**Comment by CaptainSpam** [comment]
Unfortunately, I can't do this.  Legally, at least; the terms of service for the Google Maps API prevents me from using the map images generated from it for anything other than displaying to the user.  Dumping it out to an image with the infobox stamped on it would be right out.

I'm at least assuming this issue was referring to the map, at least, since you can send photos to the wiki that get stamped with your current location.  As an alternative, most Android phones allow screenshots from a system level (on my Nexus 5, at least, pressing volume down and power at once for a second does it), and you could send that as an image.
