### ISSUE TITLE
Invalid XML sent from wiki

### ISSUE THREAD

**Issue by cyclingzealot** [CaptainSpam/geohashdroid#50]
When attempting to post a message or upload picture, at login, I get login failure then the message "Invalid XML sent from wiki".

I've checked my login credentials.

Running Geohash Droid 0.7.20 .  The android store did not offer an upgrade.

**Comment by CaptainSpam** [comment]
Drat.  I was afraid something like this would happen.  That's why I haven't released the completely revamped version yet, as it still uses the old wiki code and I wasn't sure if the actual wiki changed at all (and I didn't have a decent hashpoint nearby to test it without asking the admins to delete a test post).

Looks like I'll have to give up on waiting for a hashpoint and just ask the wiki admins if I can make test posts to sort this out.

**Comment by CaptainSpam** [comment]
Sorry it took so long to find the time (and a hashpoint) to work this out, but I think I've got it (as per 68480185ba4f528b1312f744e5f5a0f2eba1eda6).  But, since wiki posting was actually the last step in making sure the newly-revamped Geohash Droid was working, you'll probably see this fixed when the rest of the interface changes, which should be soon.

**Comment by CaptainSpam** [comment]
There we go.  Version 0.9.0 is now in the play store.  That should fix wiki posting, among many other things.  Enjoy!

**Comment by cyclingzealot** [comment]
I can confirm that this works.
See http://wiki.xkcd.com/geohashing/2015-12-01_45_-75
