### ISSUE TITLE
Infobox on uploaded picture is HUGE

### ISSUE THREAD

**Issue by ThomDenholm** [CaptainSpam/geohashdroid#55]
Subject says it all.

See http://wiki.xkcd.com/geohashing/File:2016-01-18_47_-122_thomcat_1453153921731.jpg for an example of reported problem. Nexus 6, same problem in portrait or landscape.

Previous implementations had a smaller, more reasonable overlay. Is it my changing phones?

See http://wiki.xkcd.com/geohashing/File:2014-11-20_41_-87_thomcat_1416500290791.jpg - Nexus 5 and http://wiki.xkcd.com/geohashing/File:2012-10-22_47_-122_15-52-35-476.jpg - Samsung M910 for changes over the years. The last was the most preferable to me.

Perhaps unrelated, there is no option to attach location data to upload anymore - it happens automatically if picture overlay is used, and doesn't if it isn't.  Would prefer to have that as a separate option.

**Comment by CaptainSpam** [comment]
Huh.  That's really weird, it's as if it's trying to scale it for the display size, despite the fact I am definitely telling it not to.

Though, looking it over, I may have an idea what might be going wrong.  However, since this isn't happening on my devices (Nexus 5 and Nexus 9), nor is it doing this on the emulators, I might need you to run a test on your Nexus 6 once I've got an APK ready to run.

**Comment by CaptainSpam** [comment]
Okay... I think this should do it.  I've attached an APK from the logcat branch.  This should make another launcher icon (stickfigure guy will be carrying a red bug instead of a map) and not mess with your current install.  Hopefully this REALLY tells it not to scale up the images.  Could you give this a test with a new image and let me know if it works?

(contained in a zipfile, as GitHub doesn't allow me to directly attach APKs)

[GeohashDroid-scalefix01.zip](https://github.com/CaptainSpam/geohashdroid/files/95250/GeohashDroid-scalefix01.zip)

**Comment by ThomDenholm** [comment]
Yup, that does the trick. Results in the image gallery at http://wiki.xkcd.com/geohashing/2016-01-18_47_-122 - Thanks!

**Comment by CaptainSpam** [comment]
Ah, good!  I'll see about getting a release out soon, then.  Thanks!
