### ISSUE TITLE
Nearby notification triggers a day late (for graticules east of the border?)

### ISSUE THREAD

**Issue by ephphatha** [CaptainSpam/geohashdroid#64]
I've noticed I get nearby notifications at midnight local time (AEST, UTC+10) at the end of the day when a hash fell in a marked location.

For example the June 5th hash for 33S149E landed ~5km from the city centre but no notification fired until 00:00 June 6th. The notification takes me to the map with June 5th as the selected day.

If I "Try Tomorrow" or open the date menu and select "Today" I can see the June 6th hash which falls in farmland 40km away from the city centre.

**Comment by CaptainSpam** [comment]
Huh.  That is rather strange, but admittedly, when I made the Known Locations notification stuff, I did only use non-30W hashes for testing.  That could very well be the problem.

I'll give it a look to see what I can do with it.

**Comment by ephphatha** [comment]
Had this come up again on Saturday, the notification actually triggers at 2330 local time (which makes sense given it's 14 hours offset from 930 EDT). The notification fired for Saturdays hash the night of instead of Friday night as would be expected. It seems to be correctly offsetting the date to get the right hash for a weekend day (I didn't get further notifications for the same point Sunday/Monday), just not picking the most appropriate date that would be relevant given the time the notification fires.

**Comment by CaptainSpam** [comment]
Sorry about that, got a bit distracted by other issues.  I'll try to set up a testing environment which should hopefully get me a bit more data.  By which I mean set up a grid of known locations in 33S 149E on my debug build to make sure it should trigger every day. :-)

**Comment by CaptainSpam** [comment]
One question, though... looking over my code, I may have made an unrelated mistake somewhere.  Has a known location notification EVER given you the correct date and hashpoint for a 30W graticule?

**Comment by ephphatha** [comment]
I can't recall ever getting a notification for the expected day. I only get a notification every couple of months on average but they've always been for that days location, not the one generated by the most recent stock data.

**Comment by CaptainSpam** [comment]
Gotcha.  What I was thinking of was sort of a long shot anyway.

**Comment by CaptainSpam** [comment]
This morning, with my debug build blanketing 33S 149E with known locations, I did get a notification, but when I tapped it, I got the correct date out of it.

However, as you reminded me, 0930 EDT would be 2330 AEST, a half-hour before midnight.  Given I live in EDT, my phone triggered the check (and threw up the notification) at 0930 today with plenty of time left in the day.  However, your phone would've triggered with only a half-hour left.  So, I'm getting this feeling it's in the date-adjusting code for the stock alarm.  Which is a shame, I thought I accounted for this when I originally wrote that.  Guess I might be mistaken.

I'll see if there's anything I missed.  In fact, I might have an old phone I can jury-rig into believing it's in AEST to properly test this.

**Comment by CaptainSpam** [comment]
Aha!  Sure enough, I think that's it.  In doKnownLocations() in AlarmService, the Calendar object it's using to decide what notifications to send up is just grabbed from Calendar.getInstance(), which will get "today".  You can ignore that if you're not looking at the code, but the upshot of it is, since you're in AEST, "today" will be relative to the fact that it's 2330, meaning yesterday for practical purposes.  I'm pretty sure all it needs to do is act as if it's from the same date as the stock fetch.

Fortunately, I think this should be an easy fix, but it might take me at least a couple days of testing to make sure it's doing the right thing.

**Comment by CaptainSpam** [comment]
Wait, hold on... I think I got that backward.  AEST is *ahead* of EDT, right?  Hm, then this probably won't work as planned...

Still, I'm quite certain it's just a matter of deciding what "today" is.  Still working on it.

**Comment by ephphatha** [comment]
Yeah, I'd been looking at that code and saw the comment saying the date offset was being handled elsewhere in the call stack, so I figured it wasn't the issue. Date/time stuff is confusing 😛

**Comment by CaptainSpam** [comment]
Okay... I think I've got an idea:

The entire reason the 30W Rule exists in the first place is because, by the time the NYSE opens, it's too late in the day to do much about it if you live in time zones out that far.  AEST is just one of the more extreme cases of that fact.  By the nature of the 30W Rule, tomorrow's hashpoints are known in 30W regions well in advance.  So, I'm thinking it makes sense to make the notifications always return tomorrow's hashpoints if it's looking at 30W known locations, as the stock alarm will always trigger at 0930 ET, which, much like the original reason for the rule, is too late in the day for 30W regions anyway.

All I have to do is make sure this logic works for, say, New Zealand, where it's already tomorrow by the time the stock alarm hits.

**Comment by CaptainSpam** [comment]
It's in the repo now.  I'll just let it test out tomorrow to make sure it works, then I'll bundle it up for the Play Store.

**Comment by CaptainSpam** [comment]
And there we go!  I just pushed it out to the Play Store and put the APK in the Releases section of GitHub.  Let me know if (when) it works right on your end!

Thanks for the issue report!

**Comment by ephphatha** [comment]
I was a bit late checking my phone today but I had a notification that fired on the 10th saying the hashpoint for the 11th was nearby, looks like it's working fine :)

**Comment by CaptainSpam** [comment]
Awesome.  Thanks for the report, then!
