### ISSUE TITLE
UI elements are misplaced on Android 15

### ISSUE THREAD

**Issue by coyotebush** [CaptainSpam/geohashdroid#89]
I just upgraded to Android 15, which [enforces edge-to-edge by default](https://developer.android.com/about/versions/15/behavior-changes-15#window-insets).

Now the map header overlaps my system status bar:

![Screenshot_20241023-183926](https://github.com/user-attachments/assets/32349e9b-6458-4069-9346-47ecd427ca34)

And the preferences header obscures some of the items:

![Screenshot_20241023-184002](https://github.com/user-attachments/assets/8385747e-3272-420a-99ea-3f41cc34261c)

**Comment by CaptainSpam** [comment]
Aha.  You're right, I didn't count on that change.  I'll have to read up on how to fix that.  Thanks for the report, though!

**Comment by CaptainSpam** [comment]
All righty, I figured out how to get insets into the UI so it won't conflict with system UI elements (c9c4d564a59d39efb8123f092cd8f90f41d562d7).  That'll work, at least, but the system icon theme (also the navigation buttons and clock text) are pure white in all cases, including in the light theme.  Still working on that.

**Comment by CaptainSpam** [comment]
I think I got it (426a7a4).  Seems a bit of a hack job, but I'm getting the feeling Android isn't quite expecting me to be maintaining compatibility to... egads, Kitkat?  Wow, **I** didn't really expect to be maintaining compatibility that far back. 
 Regardless, since this is a bit important of a bug, I'll hopefully get it out the door tomorrow.

**Comment by CaptainSpam** [comment]
There we go.  Version 0.9.6.4 is now up here, and will soon be up on Play.  Thanks!
